version: 3.6.2
username: stackato
password: stackato
hostname: stefan.com
enable_gui: true
provision_logs: /home/stackato/provision.log
debug: true

network:
  mode: nat
  cidr: 10.0.1.0/24

core:
  roles: core,controller
  memory: 2048
  cpu: 2

nodes:
  - name: dea
    roles: dea
    number: 1
    memory: 2048
    cpu: 2
    proxied: false

  - name: dataservice
    roles: dataservices
    number: 0
    memory: 2048
    cpu: 2
    proxied: false

  - name: router
    roles: router
    number: 0
    memory: 2048
    cpu: 1
    proxied: false

  - name: controller
    roles: controller
    number: 0
    memory: 2048
    cpu: 1
    proxied: false
